//
// Created by Brendon on 2/5/2026.
//

#pragma once
#include "engine/Export.h"

class ENGINE_API IModelObject {
public:
    IModelObject();
    IModelObject(IModelObject const &);

    static COFlags::TYPE const GetDefaultCOFlags();
    static __int64 GetSkinTagsFromStr(char const *);
    static bool MeshAndSkinExists(ttl::string_base<char> const &,ttl::string_base<char> const &);
    static bool MeshExist(ttl::string_base<char> const &);
    static void CollectMeshSkins(ttl::string_base<char> const &,bool,ttl::vector<ttl::string_base<char> > &);

    void AdjustExtentsToAllElements(bool,bool);
    void AllowSkinsToModifyElementFlags(int,bool);
    Anim::IPoseElement * AnimGetMeshPoseElement();
    Anim::IPoseElement const * AnimGetMeshPoseElement() const;
    void ApplyMorphInCylinder(vec3 const &,vec3 const &,float,bool,vec4 const &);
    void ApplyMorphInSphere(vec3 const &,float,bool,vec4 const &,float);
    void ApplyMorphToAllVertices(vec4 const &,EMorphApplyMode::TYPE);
    bool AreSkinsAllowedToModifyElementFlags(int) const;
    void AttachChildToMeshElement(IControlObject *,int,bool);
    int AttachSound(int,SSoundParameters &,vec3 const &);
    int AttachSound(int,ttl::string_base<char> const &,bool,float,float,vec3 const &,float);
    bool CharacterPresetExists(ttl::string_base<char> const &) const;
    void ClearMimicMorphTargets();
    void CollectUsedTextures(ttl::vector<ttl::string_base<char> > &);
    void CopyElementsPosition(IModelObject *);
    int CreateMeshPartCloth(ttl::string_base<char> const &,bool);
    bool DeleteAllMeshPartCloths();
    bool DeleteMeshPartCloth(ttl::string_base<char> const &);
    bool DeleteMeshPartCloth(int);
    void DisableEyesControl();
    void DisableFaceMimicOnMovie(bool);
    void DissolveObject(bool);
    void DumpAnims();
    void ElementSetWorldMatrixFromQuatPos(int,vec3 const &,float,vec3 const &);
    bool EnableCollisionsElement(int,bool);
    bool EnableElementPhysics(int,bool,bool);
    bool EnableElementTraceColl(int,bool);
    void EnableHierarchySerialization(bool);
    void EnableRendering(bool);
    void EnableRenderingScene(bool);
    void EnableRenderingShadows(bool);
    void EnableUpdateExtents(bool);
    void ExecuteAnimActions(int,int,TAnimId, const *,unsigned int);
    int FindMeshPartCloth(ttl::string_base<char> const &) const;
    void ForceUpdateAnimations();
    void FromUpForwardPosElementLocal(int,vec3 const &,vec3 const &,vec3 const &);
    void FromUpForwardPosElementWorld(int,vec3 const &,vec3 const &,vec3 const &);
    IAnimBind * GetAnimBind();
    IAnimBind const * GetAnimBind() const;
    float GetAnimTimeDelta() const;
    ttl::string_base<char> GetAnimationFile(ttl::string_base<char> const &);
    void GetAnimationNames(ttl::map<ttl::string_base<char>,TAnimId,ttl::less<ttl::string_base<char> >,ttl::allocator> &);
    vec3 GetBoneDirVector(unsigned char) const;
    unsigned char GetBoneIDFromMeshElem(int) const;
    vec3 GetBoneJointPos(unsigned char) const;
    vec3 GetBonePerpVector(unsigned char) const;
    ttl::string_base<char> GetCharacterName(unsigned int) const;
    void GetCharacterNames(ttl::string_base<char> &,ttl::string_base<char> &);
    int GetChildrenElementsNumber(int) const;
    int GetCurrentLOD() const;
    union LodDissolves::SState GetCurrentLodState() const;
    int GetElementChild(int) const;
    extents GetElementExtentsInWorld(int) const;
    extents GetElementExtentsLocal(int) const;
    unsigned int GetElementFlags(int) const;
    int GetElementID(ttl::string_base<char> const &) const;
    int GetElementID(char const *) const;
    void GetElementInvWorldMatrix(int,mtx34 &) const;
    void GetElementLocalMatrices(int const *,unsigned int,mtx34 *);
    mtx34 const & GetElementLocalMatrix(int) const;
    vec3 GetElementLocalPos(int) const;
    ttl::string_base<char> GetElementName(int) const;
    char const * GetElementNameCStr(int) const;
    int GetElementNext(int) const;
    int GetElementOrBoneElementID(char const *) const;
    int GetElementParent(int) const;
    mtx34 const & GetElementWorldMatrix(int) const;
    vec3 GetElementWorldPos(int) const;
    int GetElementsNumber() const;
    int GetFaceMimicMode() const;
    void GetFaceMimicNames(ttl::string_base<char> const &,ttl::vector<ttl::string_base<char> > &) const;
    char GetForcedAnimLod() const;
    IInverseKinematicsObject * GetIkObject();
    IInverseKinematicsObject const * GetIkObject() const;
    float GetLastAnimApplyTime() const;
    float GetLastAnimUpdateTime() const;
    float GetLodDissolveStep() const;
    vec4 const & GetMeshAttribute(unsigned int) const;
    mtx34 const & GetMeshAttributeMtx(unsigned int) const;
    unsigned int GetMeshAttributesCount() const;
    vec4 const & GetMeshColor(unsigned int) const;
    int GetMeshElemFromBoneID(unsigned char) const;
    void GetMeshElementsMatrices(ttl::vector<mtx34> &) const;
    unsigned int GetMeshElementsMatricesCount() const;
    int GetMeshElementsState(ttl::vector<unsigned char> &,ttl::vector<int> const &) const;
    int GetMeshElementsStateSize(ttl::vector<int> const &) const;
    float GetMeshLodDistance(int) const;
    ttl::string_base<char> GetMeshName() const;
    float GetMeshSize() const;
    SMeshVisibilityParams const * GetMeshVisibilityParams() const;
    float GetMeshVisibilityRange();
    void GetMorphWeightPresetsByMask(char const *,ttl::vector<unsigned int> &,vec4 const &);
    bool GetMorphWeightTable(ttl::vector<unsigned char> &) const;
    int GetMorphWeightTableSize() const;
    int GetMorphWeightsCount();
    char const * GetMorphWeightsName(unsigned int);
    static CRTTI const * GetNativeClass();
    unsigned int GetNumCollisionHullFaces() const;
    unsigned int GetNumCollisionHullPrimitives() const;
    unsigned int GetNumCollisionHullVertices() const;
    unsigned int GetNumMorphWeightPresets() const;
    unsigned int GetNumSurfaceParams() const;
    unsigned int GetNumTraceHullFaces() const;
    unsigned int GetNumTraceHullPrimitives() const;
    unsigned int GetNumTraceHullVertices() const;
    ttl::string_base<char> GetSkin() const;
    unsigned int GetSkinCount() const;
    __int64 GetSkinMustHaveTags() const;
    __int64 GetSkinMustNotHaveTags() const;
    ttl::string_base<char> GetSkinName(unsigned int) const;
    ttl::string_base<char> GetSkinName() const;
    int GetSkinSeed() const;
    float GetSpeechLength(char const *,char const *) const;
    SSurfParams * GetSurfaceParams() const;
    int GetTraceCollType() const;
    void HackPABlender_BlockAnimation(ttl::vectorm<58,bool> const &);
    void HackPABlender_UnblockAnimation(ttl::vectorm<58,bool> &);
    bool HideElement(int);
    void HideElementsByMask(bool,ttl::string_base<char> const &);
    bool InitAnimSeqFile(ttl::string_base<char> const &);
    bool IsBiped() const;
    bool IsDefaultMeshLoaded();
    bool IsElementABone(int);
    bool IsElementCollsionsEnabled(int);
    bool IsElementHidden(int) const;
    bool IsElementIDValid(int) const;
    bool IsElementPhysicsEnabled(int);
    bool IsElementTraceCollEnabled(int);
    bool IsFaceMimicDisabledOnMovie() const;
    bool IsMeshPartClothSleeping(ttl::string_base<char> const &) const;
    bool IsObjectDissolved() const;
    bool IsObjectOnSomeMovie();
    bool IsPlayingSpeech() const;
    bool IsRenderable() const;
    bool LoadFaceMimicScript();
    void LoadMesh(bool);
    void LoadMeshElements(ISGChunk *);
    void MPC_AddJointToObject(ttl::string_base<char> const &,ttl::string_base<char> const &,IModelObject *,ttl::string_base<char> const &);
    void MPC_AddJointToStaticEnvironment(ttl::string_base<char> const &,ttl::string_base<char> const &);
    void MPC_EnableRigidMeshSynchro(int,bool);
    void MPC_EnableStandaloneMode(ttl::string_base<char> const &,bool);
    void MPC_EnableSynchroWithPhysics(int,bool);
    bool MPC_FixNodePos(int,int,int,IModelObject *,int,vec3 const &);
    vec2 MPC_GetNodeStressMul(int,int,int) const;
    bool MPC_IsFrozen(int);
    bool MPC_SetAdditionalForce(int,vec3 const &);
    void MPC_SetRuntimeStretchMul(ttl::string_base<char> const &,float);
    void MPC_SetWindInfluence(ttl::string_base<char> const &,float);
    bool MPC_SynchroMPCFromMesh(int);
    bool MeshPartClothExists(int) const;
    void MeshUseDefaultVisibilityParameters();
    float MorphWeightGet(unsigned int);
    void MoveElementBoxSide(int,int,float);
    void MoveElementBoxSides(int,vec3 const &,vec3 const &);
    void MoveElementBoxSides(int,float,float,float,float,float,float);
    bool PlayMorph(TAnimId,float,float,float,float,bool);
    bool PlaySpeech(SSpeechParams &);
    bool PlaySpeech(ttl::string_base<char> const &,ttl::string_base<char> const &,ttl::string_base<char> const &,ttl::string_base<char> const &,float,float,float,bool,unsigned int);
    vec3 PointLocalToWorld(int,vec3 const &);
    vec3 PointWorldToLocal(int,vec3 const &);
    bool RaytestMe(vec3 const &,vec3 &,unsigned short,unsigned int);
    bool RaytraceMe(SCollision *,vec3 const &,vec3 &,unsigned short,unsigned int);
    bool ReplaceMaterial(ttl::string_base<char> const &,ttl::string_base<char> const &);
    void ResetBoneAndDescendantsToReferenceFrame(int);
    void ResetBonesExtentsToReferenceFrame();
    void ResetBonesToReferenceFrame(bool);
    void ResetElementsDescendantsToReferenceFrame(int);
    void RotateElement(int,vec3 const &,float);
    void SaveMeshElements(ISGChunk *);
    void SetBestGeomLods();
    void SetBoneOrientation(unsigned char,vec3 const &,vec3 const &);
    void SetCharacterNames(ttl::string_base<char> const &,ttl::string_base<char> const &);
    void SetDontApplyAnim(bool);
    void SetElementExtentsLocal(extents const &,int);
    void SetElementLocalMatrices(int const *,unsigned int,mtx34 const *);
    void SetElementLocalMatrix(int,mtx34 const &);
    void SetElementLocalPos(int,vec3 const &);
    void SetElementWorldMatrix(int,mtx34 const &);
    void SetElementWorldPos(int,vec3 const &);
    void SetExtentsLocal(extents const &);
    void SetEyesAngles(ttl::string_base<char> const &,float,float,float,float,float);
    void SetEyesDebugLevel(int);
    void SetEyesDirection(ttl::string_base<char> const &,vec3 const &,float,float,float);
    bool SetFaceMimicHeadMoveMultiplier(float);
    void SetFaceMimicMode(int);
    bool SetFaceMimicPreset(ttl::string_base<char> const &);
    void SetForcedAnimLod(char);
    bool SetIKConstraintsPreset(ttl::string_base<char> const &,float);
    void SetLodDissolveStep(float);
    void SetLodStateForSpawnedObjects(union LodDissolves::SState);
    void SetMeshAttribute(unsigned int,vec4 const &);
    void SetMeshAttributeMtx(unsigned int,mtx34 const &);
    void SetMeshColor(unsigned int,vec4 const &);
    void SetMeshCullSizeEnable(bool);
    bool SetMeshElementsMatrices(ttl::vector<mtx34> const &);
    int SetMeshElementsState(ttl::vector<unsigned char> const &,ttl::vector<int> const &,bool,bool);
    void SetMeshLodDistance(int,float);
    void SetMeshName(ttl::string_base<char> const &);
    void SetMeshVisibilityRange(float);
    bool SetMorphWeightPreset(char const *);
    bool SetMorphWeightPresetByIndex(unsigned int);
    bool SetMorphWeightTable(ttl::vector<unsigned char> &);
    void SetPivotPointFromElement(int);
    bool SetSkin();
    void SetSkinMustHaveTags(__int64);
    void SetSkinMustNotHaveTags(__int64);
    void SetSkinName(ttl::string_base<char> const &);
    bool SetSkinNoCharacterPreset();
    void SetSkinSeed(int);
    void SetSpeech3DLevel(float);
    void SetSpeechVolume(float);
    void SetTraceCollType(int);
    void SetWeightsMultiplier(float);
    bool ShouldApplyAnim() const;
    void ShowCollisionHull(bool);
    void ShowElementBox(ttl::string_base<char> const &);
    void ShowElementBoxes(bool);
    void ShowElementBoxesFrom(ttl::string_base<char> const &);
    void ShowElementBoxesFromTo(ttl::string_base<char> const &,ttl::string_base<char> const &);
    void ShowElementBoxesTo(ttl::string_base<char> const &);
    void ShowExtents(bool);
    bool SkinExists(ttl::string_base<char> const &);
    void StartFaceMimic();
    void StartLookingAtCamera(ttl::string_base<char> const &,float,float,float);
    void StartLookingAtObject(ttl::string_base<char> const &,IModelObject *,ttl::string_base<char> const &,float,float,float);
    void StartLookingAtWorldPoint(ttl::string_base<char> const &,vec3 const &,float,float,float);
    void StartLookingStraightAhead(ttl::string_base<char> const &,float,float,float);
    bool StartMimic(ttl::string_base<char> const &,float,float,float,float,float);
    void StopAllMimics();
    void StopAnimActions(int,TAnimId, const *,float);
    void StopFaceMimic();
    void StopMimic(ttl::string_base<char> const &);
    void StopMorph(TAnimId);
    void StopSpeech(float);
    void StopSystemsUsingMeshElements();
    CModelObject * ToCModelObject();
    CModelObject const * ToCModelObject() const;
    bool UnhideElement(int);
    vec3 VectorLocalToWorld(int,vec3 const &);
    vec3 VectorWorldToLocal(int,vec3 const &);

    virtual ~IModelObject();
    virtual EObjectToSimpleObjectsQueryResult::TYPE CanGoToSimpleObjectsEditor() const;
    virtual IInverseKinematicsObject * CreateIkObject(float);
    virtual void DestroyIkObject();
    virtual void DissolveObjectProgress(float,bool);
    virtual void EnableMotionBlur(bool);
    virtual void GatherMeshAndSkinName(ttl::string_base<char> &,ttl::string_base<char> &) const;
    virtual char const * GetFaceMimicFile() const;
    virtual bool GetMeshDataForSimpleObjectsEditor(ttl::string_base<char> *,ttl::string_base<char> *,__int64 *,__int64 *,int *);
    virtual float GetWaterCurrentSpeed();
    virtual void OnAnimBindCreated();
    virtual void OnAnimBindDestroyed();
    virtual void OnAnimEvent(AnimEventInfo const &);
    virtual void OnMeshPartClothCreated(ttl::string_base<char> const &,int);
    virtual void SetEngineObject(CGSObject *);
    virtual void SetupMeshPartClothes(bool,bool);
};