cmake_minimum_required(VERSION 3.20)
project(DLCE LANGUAGES CXX)

option(STEAM_PLATFORM "Build Steam version" ON)
if (STEAM_PLATFORM)
  add_compile_definitions(STEAM_PLATFORM=1)
endif()

if (CMAKE_COMPILER_IS_GNUCXX)
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static")
    set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -static")
endif()
add_subdirectory(libs/Engine)
add_subdirectory(libs/Filesystem)
add_subdirectory(libs/GameDLL)
add_subdirectory(libs/Steam)

add_subdirectory(DyingLightGame)
add_subdirectory(ExampleMod)
add_subdirectory(MFCProject)