#pragma once
#include "IUIElement.h"

class __declspec(dllimport) IUIElementControl {
public:
	IUIElementControl(IUIElementControl const&);
	IUIElementControl();
	bool CanBeSelected() const;
	bool CanFocus();
	bool CanProcessCapturedKeyboard() const;
	bool CanProcessCapturedMouse() const;
	void CaptureJoy();
	void CaptureKeyboard();
	bool CaptureMouse();
	bool CheckTabForwardOnLockNavigation(EElementControlNavigation::TYPE);
	void ClearCaptureJoy();
	void ClearCaptureKeyboard();
	void ClearCaptureMouse();
	void ClearPressKey();
	void Deselect();
	IUIHtmlPresenter* FindHtmlPresenter(int, bool);
	IUITextPresenter* FindTextPresenter(int, bool);
	void FocusNextElement();
	bool FollowNavigation(EElementControlNavigation::TYPE, bool, bool);
	bool GetAllowMultiSelect() const;
	int GetAlternativePressKey() const;
	bool GetDisableFocusRecursion() const;
	bool GetDisableTabNavigation() const;
	IUIElementControl* GetFocus();
	IUIElementControl* GetFocusElement();
	float GetInstanceCurrentTime() const;
	static CRTTI const* GetNativeClass();
	IUIElementControl* GetNavigationConnection(EElementControlNavigation::TYPE);
	ttl::string_base<char> GetNavigationConnectionString(EElementControlNavigation::TYPE);
	int GetPressKey();
	ttl::string_base<char> GetTexture(int);
	vec4 GetTextureColor(int);
	IUIVisual* GetVisual();
	ttl::string_base<char> const& GetVisualName() const;
	bool IsAPressDefault();
	bool IsDeselected();
	bool IsDisabled();
	bool IsEnabled();
	bool IsFocus();
	bool IsInstanceAnimationPlaying() const;
	bool IsInstanced() const;
	bool IsPressKey(int);
	bool IsSelected();
	bool IsTabForwardOnDisable() const;
	bool IsTabForwardOnLockNavigation() const;
	bool IsUnfocusedInput();
	void PlayInstanceAnimation();
	void ProcessCapturedMouseMove(bool);
	void ProcessInputs(bool);
	void ProcessJoy(bool, bool);
	void ProcessKb(bool, bool);
	void ProcessMouse(bool, bool);
	void ProcessMouseBtnOutside(bool);
	bool ProcessNavigationMessage(EUIMessage::SUIMessage*);
	bool ProcessingInputs() const;
	bool ProcessingJoy() const;
	bool ProcessingKb() const;
	bool ProcessingMouse() const;
	bool ProcessingMouseBtnOutside() const;
	static void RegisterRTTI();
	void Select();
	void SendMessageA(EUIMessage::SUIMessage&);
	void SendMessageA(int, IUIElement*);
	void SendMessageA(int, IUIElement*, int);
	void SendMessageA(int, IUIElement*, float);
	void SendMessageA(int, IUIElement*, float, int);
	void SendMessageA(int, IUIElement*, float, float);
	void SendMessageA(int, IUIElement*, float, float, int);
	void SetAPressDefault(bool);
	void SetAllowMultiSelect(bool);
	void SetAlternativePressKey(int);
	void SetCanBeSelected(bool);
	void SetDisableFocusRecursion(bool);
	void SetDisableTabNavigation(bool);
	void SetDisabled(bool);
	void SetFocus(bool, EUIFocusChangeReason::TYPE);
	void SetFocusElement(IUIElementControl*, EUIFocusChangeReason::TYPE);
	void SetFocusElementSetup(IUIElementControl*, EUIFocusChangeReason::TYPE);
	void SetNewNavigationConnection(ttl::string_base<char> const&, EElementControlNavigation::TYPE);
	void SetNewNavigationConnection(IUIElementControl*, EElementControlNavigation::TYPE);
	void SetTabForwardOnDisable(bool);
	void SetTabForwardOnLockNavigation(bool);
	void SetTextColor(vec3 const&);
	void SetTextColor(vec4 const&, int);
	void SetTextColor(float, float, float, float);
	void SetVisual(ttl::string_base<char> const&);
	void StopInstanceAnimation();
	CUIElementControl* ToCUIElementControl() const;
	void TryPersonaliseVisual();

	/*
	virtual ~IUIElementControl();
	virtual bool CanBeEnabled();
	virtual bool CanGroup() const;
	virtual void ClearText(int);
	virtual void FillElementInstanceParameters(IUIElement*);
	virtual bool ForceFocus();
	virtual void* GetElementData();
	virtual unsigned int GetElementType();
	virtual CRTTI const* GetEngineRTTI() const;
	virtual CRTTI const* GetRTTI() const;
	virtual ttl::string_base<char> const& GetText(int);
	virtual ttl::string_base<wchar_t> const& GetTextExplicit(int);
	virtual bool IsControl() const;
	virtual void OnChildTextChange(int);
	virtual bool OnClickLB(float, float);
	virtual bool OnClickRB(float, float);
	virtual void OnDeselect();
	virtual void OnDeselectChild(IUIElementControl*);
	virtual void OnDisable();
	virtual bool OnDisableChild(IUIElementControl*);
	virtual void OnEnable();
	virtual void OnEnableChild(IUIElementControl*);
	virtual void OnFocusClear(EUIFocusChangeReason::TYPE);
	virtual void OnFocusClearChild(IUIElementControl*);
	virtual void OnFocusElementChange(EUIFocusChangeReason::TYPE);
	virtual void OnFocusSet(EUIFocusChangeReason::TYPE);
	virtual void OnFocusSetChild(IUIElementControl*);
	virtual void OnInit();
	virtual void OnInitEditor();
	virtual void OnInputJoyAxis(int, int, float);
	virtual void OnInputJoyAxisUnfocused(int, int, float);
	virtual void OnInputJoyButton(int, int, bool);
	virtual void OnInputJoyButtonUnfocused(int, int, bool);
	virtual void OnInputJoyState(int, bool);
	virtual void OnInputKey(int, bool, int);
	virtual void OnInputMouseButtonCursor(int, int, float, float);
	virtual void OnInputProcessingChange();
	virtual void OnInputTouchPad(int, TouchPadEvent const&);
	virtual bool OnKeyPressed(int, int);
	virtual bool OnKeyPressedUnfocused(int, int);
	virtual bool OnKeyReleased(int, int);
	virtual bool OnKeyReleasedUnfocused(int, int);
	virtual void OnLBDown(float, float);
	virtual void OnLBDownOut(float, float);
	virtual void OnLBUp(float, float);
	virtual void OnLBUpOut(float, float);
	virtual void OnMouseEnter(float, float);
	virtual void OnMouseLeave(float, float);
	virtual void OnMouseMove(float, float, int);
	virtual void OnMouseMoveOut(float, float, int);
	virtual void OnMouseWheel(int, float);
	virtual void OnRBDown(float, float);
	virtual void OnRBDownOut(float, float);
	virtual void OnRBUp(float, float);
	virtual void OnRBUpOut(float, float);
	virtual void OnSelect();
	virtual void OnSelectChild(IUIElementControl*);
	virtual void OnVisualChange();
	virtual bool ProcessMessage(EUIMessage::SUIMessage*);
	virtual void ReapplyVisual();
	virtual void SetCanFocus(bool);
	virtual void SetDisable(bool);
	virtual void SetElementData(*);
	virtual void SetEnable(bool);
	virtual void SetEngineObject(gui::CObject*);
	virtual void SetHtmlSource(SHtmlSource const&, int);
	virtual void SetPressKey(EJoy::TYPE);
	virtual void SetPressKey(EKey::TYPE);
	virtual void SetText(ttl::string_base<char> const&, int);
	virtual void SetTextExplicit(ttl::string_base<wchar_t> const&, int);
	virtual bool SetTexture(ttl::string_base<char> const&, int);
	virtual void SetTextureColor(vec4 const&, int);
	virtual void SetUnfocusedInput(bool);
	*/
};