#include <pch.h>
#include "Loader.h"
//#include "Core/Sdk/Engine/engine.h"
//#include "Core/Sdk/Engine/resource.h"
#include "Core/Util/Directory.h"
#include "Core/Util/String.h"
#include "Hooks.h"
#include "Core/Sdk/Filesystem/Filesystem.h"


namespace Loader {
    std::vector<HMODULE> NativeMods;
    static std::vector<Mod> ModList;

    void IndexMods()
    {

        /*
        * 
        * Mods
        * └───ExampleMod
        *     ├───Libs
        *     │       //any dll or asi mod will be loaded here
        *     │       ExampleLowLevel.dll
        *     │
        *     ├───MatPacks
        *     │       //shaders and such, must end with _dx11.mp
        *     │       local_dx11.mp
        *     │
        *     ├───Paks
        *     │       Slums_Minecraft_Frog.pak
        *     │
        *     └───Rpacks
        *         │   //large optimised texture pack, generated by ResPackCompilerConsole_x64_rwdi.exe, supports streaming, must end in _pc.rpack
        *         │   House_textures_pc.rpack
        *         │
        *         └───Tiny
        *                 //individual small assets, generated by the offical editor (loaded into ram all at once), can load rpaco and rpacz also
        *                 frog.rpack
        *                 frog_albedo.rpack
        *                 frog_normal.rpack
        *
        * //if you have a lot of objects in the tiny folder, you should consider compiling them into an optimised rpack
        * //large rpacks in the tiny folder will work, at the cost of being loaded entirely into ram, at once (so crashes, long loading times ect)
        * //tiny folder is mainly for patches or quick testing
        * 
        */


        std::filesystem::path WorkingPath = Utils::GetWorkingDirectory();
        std::filesystem::path ModsPath = WorkingPath / "Mods";
        std::filesystem::path GlobalPaksPath = ModsPath / "GlobalPaks";

        Utils::CreateFolder(ModsPath);
        Utils::CreateFolder(GlobalPaksPath);

        //normal mods
        for (const auto& modEntry : std::filesystem::directory_iterator(ModsPath))
        {
            std::filesystem::path ModBasePath = modEntry.path();
            std::filesystem::path LibsPath = ModBasePath / "Libs";
            std::filesystem::path PaksPath = ModBasePath / "Paks";
            std::filesystem::path RpacksPath = ModBasePath / "Rpacks";
            std::filesystem::path TinyRpacksPath = RpacksPath / "Tiny";
            std::filesystem::path MatPacksPath = ModBasePath / "Matpacks";

            if (!std::filesystem::is_directory(modEntry.status()))
                continue;


            Mod currentMod;
            currentMod.ModName = modEntry.path().filename().string();
            currentMod.IsEnabled = true;

            //this section is for a "Global" mod, which is just for loading mods not made for this loader
            //if in the "GlobalPaks" folder
            if (currentMod.ModName == "GlobalPaks")
            {
                //for each file in "GlobalPaks"
                for (const auto& file : std::filesystem::directory_iterator(ModBasePath))
                {
                    if (Utils::str_tolower(file.path().extension().string()) == ".pak")
                    {
                        SubMod pakMod;
                        pakMod.ModName = file.path().stem().string();
                        pakMod.ModType = SubMod::PAK;
                        pakMod.ModPath = file.path().string();
                        currentMod.SubMods.push_back(pakMod);
                    }
                }

                //only actually add the global "mod" if there are any paks
                if (currentMod.SubMods.size() > 0)
                    ModList.push_back(currentMod);

                continue;
            }


            // Ensure subfolders exist
            Utils::CreateFolder(LibsPath);
            Utils::CreateFolder(PaksPath);
            Utils::CreateFolder(RpacksPath);
            Utils::CreateFolder(TinyRpacksPath);
            Utils::CreateFolder(MatPacksPath);

            fs::add_source(TinyRpacksPath.string().c_str(), (FFSAddSourceFlags::ENUM)7);
            fs::add_source(RpacksPath.string().c_str(), (FFSAddSourceFlags::ENUM)7);
            fs::add_source(MatPacksPath.string().c_str(), (FFSAddSourceFlags::ENUM)7);

            // Load .dll and .asi from Libs/
            for (const auto& file : std::filesystem::directory_iterator(LibsPath))
            {
                std::string ext = Utils::str_tolower(file.path().extension().string());
                if (ext == ".dll" || ext == ".asi")
                {
                    SubMod nativeMod;
                    nativeMod.ModName = file.path().stem().string();
                    nativeMod.ModType = SubMod::ASI;
                    nativeMod.ModPath = file.path().string();
                    currentMod.SubMods.push_back(nativeMod);
                }
            }

            // Load .pak from Paks/
            for (const auto& file : std::filesystem::directory_iterator(PaksPath))
            {
                if (Utils::str_tolower(file.path().extension().string()) == ".pak")
                {
                    SubMod pakMod;
                    pakMod.ModName = file.path().stem().string();
                    pakMod.ModType = SubMod::PAK;
                    pakMod.ModPath = file.path().string();
                    currentMod.SubMods.push_back(pakMod);
                }
            }

            // Load optimised, large rpacks, ending in _pc.rpack
            for (const auto& file : std::filesystem::directory_iterator(RpacksPath))
            {
                if (Utils::str_tolower(file.path().extension().string()) == ".rpack")
                {
                    SubMod rpackMod;
                    rpackMod.ModName = file.path().stem().string();
                    rpackMod.ModType = SubMod::RPACK;
                    rpackMod.ModPath = file.path().string();
                    currentMod.SubMods.push_back(rpackMod);
                }
            }


            // Load smaller, non optimised rpacks, such as patches or "tiny" rpacks created by the devtools
            for (const auto& file : std::filesystem::directory_iterator(TinyRpacksPath))
            {
                std::string ext = Utils::str_tolower(file.path().extension().string());
                if (ext == ".rpack" || ext == ".rpaco" || ext == ".rpacz")
                {
                    SubMod tinyRpackMod;
                    tinyRpackMod.ModName = file.path().stem().string();
                    tinyRpackMod.ModType = SubMod::TINY_RPACK;
                    tinyRpackMod.ModPath = file.path().string();
                    currentMod.SubMods.push_back(tinyRpackMod);
                }
            }

            // Load .mp from MatPacks/
            for (const auto& file : std::filesystem::directory_iterator(MatPacksPath))
            {
                if (Utils::str_tolower(file.path().extension().string()) == ".mp")
                {
                    SubMod matMod;
                    matMod.ModName = file.path().stem().string();
                    matMod.ModType = SubMod::MP;
                    matMod.ModPath = file.path().string();
                    currentMod.SubMods.push_back(matMod);
                }
            }

            // Add the fully populated mod to the list
            ModList.push_back(currentMod);
        }
    }


    void LoadNativeMods()
    {
        for (auto& modInfo : ModList)
        {
            for (auto& subModInfo : modInfo.SubMods)
            {
                if (subModInfo.ModType == SubMod::ASI)
                {
                    const char* libname = subModInfo.ModPath.c_str();
                    auto HModule = LoadLibrary(libname);

                    if (HModule) {
                        auto GetPluginName = (T_GetPluginName)GetProcAddress(HModule, "GetPluginName");

                        if (GetPluginName)
                            subModInfo.ModName = GetPluginName();

                        dbgprintf("[Plugin] %s loaded: %s\n", modInfo.ModName.c_str(), subModInfo.ModPath.c_str());
                        NativeMods.push_back(HModule);
                    }
                }
            }
        }
    }


    void LoadModPaks()
    {
        for (const auto& modInfo : ModList)
        {
            //if enabled check in future

            for (const auto& subModInfo : modInfo.SubMods)
            {
                if (subModInfo.ModType == SubMod::PAK)
                {
                    const char* pakname = subModInfo.ModPath.c_str();
                    fs::add_source(pakname, (FFSAddSourceFlags::ENUM)9);

                    //dbgprintf("Added Source : %s\n", cPak);
                }
            }
        }
    }

    CResourceDataPack* LoadResourcePaks(CResourceLoadingRuntime* s_ResourceLoadingRuntime)
    {
        for (const auto& modInfo : ModList)
        {
            //if enabled check in future

            for (const auto& subModInfo : modInfo.SubMods)
            {
                if (subModInfo.ModType == SubMod::RPACK)
                {
                    auto packname = subModInfo.ModPath;
                    packname = Utils::RemoveSuffix(packname, "_pc.rpack");

                    CResourceDataPack* outPack = nullptr;

                    //discard return value, bool result
                    PackLoader::Load(
                        s_ResourceLoadingRuntime,
                        packname.c_str(),
                        &outPack,
                        EIsGlobalPack::No,
                        EIsContentPack::No,
                        EUseCachePartition::Yes,
                        EIsCrossLevelPack::Yes,
                        static_cast<EPackKind>(0) // Unused I beleve
                    );

                    return outPack;
                }
            }
        }
    }

    void LoadTinyResourcePaks(IGame* pIGame)
    {
        for (const auto& modInfo : ModList)
        {
            //if enabled check in future

            for (const auto& subModInfo : modInfo.SubMods)
            {
                if (subModInfo.ModType == SubMod::TINY_RPACK)
                {
                    ttl::string_base<char> PackPath(subModInfo.ModPath.c_str());
                    std::cout << &PackPath << std::endl;


                    //roughly the same as AssetManager* s_AssetManagerImpl's LoadAsset function 
                    pIGame->LoadPack(PackPath, true, true, nullptr);
                    dbgprintf("Added Rpack : %s\n", subModInfo.ModPath.c_str());
                }
            }
        }
    }

    void LoadMaterialPacks(CMaterialMgr* s_MaterialMgr)
    {

        for (const auto& modInfo : ModList)
        {
            //if enabled check in future

            for (const auto& subModInfo : modInfo.SubMods)
            {
                if (subModInfo.ModType == SubMod::MP)
                {
                    auto matName = subModInfo.ModPath;
                    matName = Utils::RemoveSuffix(matName, "_dx11.mp");

                    s_MaterialMgr->LoadPack(matName.c_str(), 1);
                }
            }
        }
    }

    //callbacks for native mods
    void PreInitialize() {
        for (const auto& HModule : NativeMods)
        {
            if (HModule == nullptr) {
                MessageBoxA(nullptr, "Module handle is null!", "Error", MB_ICONERROR);
                return;
            }

            auto PreInitialize = (T_PreInitialize)GetProcAddress(HModule, "PreInitialize");

            if (PreInitialize)
                PreInitialize();
        }
    }

    void PostInitialize() {
        for (const auto& HModule : NativeMods)
        {
            if (HModule == nullptr) {
                MessageBoxA(nullptr, "Module handle is null!", "Error", MB_ICONERROR);
                return;
            }

            auto PostInitialize = (T_PostInitialize)GetProcAddress(HModule, "PostInitialize");

            if (PostInitialize)
                PostInitialize();
        }
    }
}